#!/usr/bin/env python3
"""Render and verify Woof's privacy-safe operational alert policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
POLICY_PATH = ROOT / "ops" / "alerts" / "woof-api-alert-policy.v1.json"
RULES_PATH = ROOT / "ops" / "alerts" / "woof-api.rules.yml"
FIXTURES_PATH = ROOT / "ops" / "alerts" / "fixtures" / "woof-api-alert-fixtures.v1.json"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def alert_rule(
    *,
    name: str,
    expr: str,
    duration: str,
    severity: str,
    service: str,
    policy_version: str,
    operation_class: str,
    summary: str,
    description: str,
    static_release: str | None = None,
) -> list[str]:
    labels = [
        f'        severity: "{severity}"',
        f'        service: "{service}"',
        f'        operation_class: "{operation_class}"',
        f'        policy_version: "{policy_version}"',
    ]
    if static_release is not None:
        labels.append(f'        release: "{static_release}"')
    return [
        f"    - alert: {name}",
        "      expr: >-",
        *[f"        {line}" for line in expr.splitlines()],
        f"      for: {duration}",
        "      labels:",
        *labels,
        "      annotations:",
        f'        summary: "{summary}"',
        f'        description: "{description}"',
    ]


def ratio_expr(
    *,
    metric: str,
    service: str,
    window: str,
    bad_selector: str,
    ratio: float,
    minimum: int,
    extra_selector: str = "",
) -> str:
    selector_prefix = f'service="{service}"'
    if extra_selector:
        selector_prefix = f"{selector_prefix},{extra_selector}"
    bad = f"{selector_prefix},{bad_selector}"
    return "\n".join(
        [
            "(",
            f"  sum by (release) (rate({metric}{{{bad}}}[{window}]))",
            "  /",
            f"  clamp_min(sum by (release) (rate({metric}{{{selector_prefix}}}[{window}])), 0.000001)",
            f") >= {ratio}",
            "and on (release)",
            f"sum by (release) (increase({metric}{{{selector_prefix}}}[{window}])) >= {minimum}",
        ]
    )


def render_rules(policy: dict[str, Any]) -> str:
    service = policy["service"]
    version = policy["version"]
    lines = [
        "# GENERATED by .github/scripts/woof-alert-policy.py from woof-api-alert-policy.v1.json.",
        "# Do not edit thresholds here. Change the policy JSON and regenerate.",
        "groups:",
        "  - name: woof-api-operational-alerts-v1",
        f"    interval: {policy['evaluationInterval']}",
        "    rules:",
    ]

    def add(**kwargs: Any) -> None:
        lines.extend(alert_rule(service=service, policy_version=version, **kwargs))

    missing = policy["telemetryMissing"]
    missing_expr = f'absent(woof_process_uptime_seconds{{service="{service}"}})'
    for severity, duration in [
        ("warning", missing["warningFor"]),
        ("critical", missing["criticalFor"]),
    ]:
        add(
            name=f"WoofOperationalMetricsMissing{severity.title()}",
            expr=missing_expr,
            duration=duration,
            severity=severity,
            operation_class="telemetry",
            summary=f"Woof API operational metrics are missing ({severity})",
            description="The API metrics heartbeat is absent. Missing telemetry is an observability incident, not evidence of health.",
            static_release="unknown",
        )

    unknown = policy["unknownRelease"]
    add(
        name="WoofReleaseIdentityUnknownWarning",
        expr=f'woof_release_info{{service="{service}",release="unknown"}} == 1',
        duration=unknown["warningFor"],
        severity="warning",
        operation_class="release_identity",
        summary="Woof API is exporting an unknown release identity",
        description="Operational evidence is not tied to an exact 40-hex Git SHA; do not promote this process as a qualified release.",
    )

    readiness = policy["readinessFailures"]
    readiness_selector = (
        f'service="{service}",operation="{readiness["operation"]}"'
    )
    readiness_missing_expr = f"absent(woof_http_requests_total{{{readiness_selector}}})"
    for severity, duration in [
        ("warning", missing["warningFor"]),
        ("critical", missing["criticalFor"]),
    ]:
        add(
            name=f"WoofReadinessProbeMissing{severity.title()}",
            expr=readiness_missing_expr,
            duration=duration,
            severity=severity,
            operation_class="readiness",
            summary=f"Woof API readiness probe telemetry is missing ({severity})",
            description="The process may still export metrics, but no readiness probe series exists. Verify external probing before treating the service as healthy.",
            static_release="unknown",
        )
    for severity, threshold, duration in [
        ("warning", readiness["warningFailures"], readiness["warningFor"]),
        ("critical", readiness["criticalFailures"], readiness["criticalFor"]),
    ]:
        expr = (
            f'sum by (release) (increase(woof_http_requests_total{{{readiness_selector},status_class="5xx"}}'
            f'[{readiness["window"]}])) >= {threshold}'
        )
        add(
            name=f"WoofReadinessFailures{severity.title()}",
            expr=expr,
            duration=duration,
            severity=severity,
            operation_class="readiness",
            summary=f"Woof API readiness is failing ({severity})",
            description="Database-backed readiness has returned server errors within the bounded alert window for release {{ $labels.release }}.",
        )

    http = policy["http5xx"]
    for severity, ratio, duration in [
        ("warning", http["warningRatio"], http["warningFor"]),
        ("critical", http["criticalRatio"], http["criticalFor"]),
    ]:
        add(
            name=f"WoofHttp5xxRatio{severity.title()}",
            expr=ratio_expr(
                metric="woof_http_requests_total",
                service=service,
                window=http["window"],
                bad_selector='status_class="5xx"',
                ratio=ratio,
                minimum=http["minimumRequests"],
            ),
            duration=duration,
            severity=severity,
            operation_class="http_service",
            summary=f"Woof API 5xx ratio is elevated ({severity})",
            description="The bounded service-wide 5xx ratio exceeded policy for release {{ $labels.release }} after the minimum request floor was met.",
        )

    auth = policy["auth5xx"]
    auth_selector = f'operation=~"{auth["operationRegex"]}"'
    for severity, ratio, duration in [
        ("warning", auth["warningRatio"], auth["warningFor"]),
        ("critical", auth["criticalRatio"], auth["criticalFor"]),
    ]:
        add(
            name=f"WoofAuth5xxRatio{severity.title()}",
            expr=ratio_expr(
                metric="woof_http_requests_total",
                service=service,
                window=auth["window"],
                bad_selector='status_class="5xx"',
                ratio=ratio,
                minimum=auth["minimumRequests"],
                extra_selector=auth_selector,
            ),
            duration=duration,
            severity=severity,
            operation_class="auth_session",
            summary=f"Woof authentication/session server-error ratio is elevated ({severity})",
            description="Auth/session operations are returning server errors above policy for release {{ $labels.release }}. Expected login 401s are intentionally excluded.",
        )

    today = policy["todayReadP95Ms"]
    today_selector = f'service="{service}",operation=~"{today["operationRegex"]}"'
    for severity, threshold, duration in [
        ("warning", today["warningMs"], today["warningFor"]),
        ("critical", today["criticalMs"], today["criticalFor"]),
    ]:
        expr = "\n".join(
            [
                "(",
                f"  histogram_quantile({today['quantile']},",
                "    sum by (le, release) (",
                f"      rate(woof_http_request_duration_ms_bucket{{{today_selector}}}[{today['window']}])",
                "    )",
                "  )",
                f") >= {threshold}",
                "and on (release)",
                f"sum by (release) (increase(woof_http_request_duration_ms_count{{{today_selector}}}[{today['window']}])) >= {today['minimumRequests']}",
            ]
        )
        add(
            name=f"WoofTodayReadP95Latency{severity.title()}",
            expr=expr,
            duration=duration,
            severity=severity,
            operation_class="today_read",
            summary=f"Woof Today/read p95 latency is elevated ({severity})",
            description="Histogram-derived p95 latency exceeded the initial operator guardrail for release {{ $labels.release }} after the minimum sample floor was met.",
        )

    caregiver = policy["caregiverTransition5xx"]
    caregiver_selector = f'operation=~"{caregiver["operationRegex"]}"'
    for severity, ratio, duration in [
        ("warning", caregiver["warningRatio"], caregiver["warningFor"]),
        ("critical", caregiver["criticalRatio"], caregiver["criticalFor"]),
    ]:
        add(
            name=f"WoofCaregiverTransition5xxRatio{severity.title()}",
            expr=ratio_expr(
                metric="woof_http_requests_total",
                service=service,
                window=caregiver["window"],
                bad_selector='status_class="5xx"',
                ratio=ratio,
                minimum=caregiver["minimumRequests"],
                extra_selector=caregiver_selector,
            ),
            duration=duration,
            severity=severity,
            operation_class="caregiver_transition",
            summary=f"Woof caregiver transition server-error ratio is elevated ({severity})",
            description="Pet-scoped caregiver grant transitions are returning server errors above policy for release {{ $labels.release }}.",
        )

    connector = policy["connectorRejected"]
    for severity, ratio, duration in [
        ("warning", connector["warningRatio"], connector["warningFor"]),
        ("critical", connector["criticalRatio"], connector["criticalFor"]),
    ]:
        add(
            name=f"WoofConnectorRejectedRatio{severity.title()}",
            expr=ratio_expr(
                metric="woof_connector_imports_total",
                service=service,
                window=connector["window"],
                bad_selector='outcome="REJECTED"',
                ratio=ratio,
                minimum=connector["minimumImports"],
            ),
            duration=duration,
            severity=severity,
            operation_class="connector_import",
            summary=f"Woof connector rejection ratio is elevated ({severity})",
            description="Verified connector imports are being rejected above the initial operator guardrail for release {{ $labels.release }}.",
        )

    device = policy["deviceContractRejections"]
    for severity, threshold, duration in [
        ("warning", device["warningCount"], device["warningFor"]),
        ("critical", device["criticalCount"], device["criticalFor"]),
    ]:
        expr = (
            f'sum by (release) (increase(woof_device_contract_rejections_total{{service="{service}"}}'
            f'[{device["window"]}])) >= {threshold}'
        )
        add(
            name=f"WoofDeviceContractRejections{severity.title()}",
            expr=expr,
            duration=duration,
            severity=severity,
            operation_class="device_contract",
            summary=f"Woof device-contract rejections are elevated ({severity})",
            description="Untrusted device envelopes are being rejected above policy for release {{ $labels.release }}. Inspect partner transport without logging raw payloads.",
        )

    return "\n".join(lines) + "\n"


def classify_ratio(total: float, bad: float, minimum: int, warning: float, critical: float) -> str:
    if total < minimum:
        return "INSUFFICIENT_DATA"
    ratio = bad / total if total > 0 else 0
    if ratio >= critical:
        return "CRITICAL"
    if ratio >= warning:
        return "WARNING"
    return "OK"


def classify_count(value: float, warning: float, critical: float) -> str:
    if value >= critical:
        return "CRITICAL"
    if value >= warning:
        return "WARNING"
    return "OK"


def classify_fixture(policy: dict[str, Any], fixture: dict[str, Any]) -> dict[str, str]:
    sample = fixture["sample"]
    if not sample["telemetryPresent"]:
        return {
            "telemetry": "UNKNOWN",
            "release": "UNKNOWN",
            "readiness": "UNKNOWN",
            "http5xx": "UNKNOWN",
            "auth5xx": "UNKNOWN",
            "todayReadP95Ms": "UNKNOWN",
            "caregiverTransition5xx": "UNKNOWN",
            "connectorRejected": "UNKNOWN",
            "deviceContractRejections": "UNKNOWN",
        }

    readiness = policy["readinessFailures"]
    http = policy["http5xx"]
    auth = policy["auth5xx"]
    today = policy["todayReadP95Ms"]
    caregiver = policy["caregiverTransition5xx"]
    connector = policy["connectorRejected"]
    device = policy["deviceContractRejections"]

    today_state = "INSUFFICIENT_DATA"
    if sample["todayRequests"] >= today["minimumRequests"]:
        today_state = classify_count(sample["todayP95Ms"], today["warningMs"], today["criticalMs"])

    return {
        "telemetry": "OK",
        "release": "WARNING" if sample["release"] == "unknown" else "OK",
        "readiness": classify_count(
            sample["readinessFailures"],
            readiness["warningFailures"],
            readiness["criticalFailures"],
        ),
        "http5xx": classify_ratio(
            sample["httpRequests"],
            sample["http5xx"],
            http["minimumRequests"],
            http["warningRatio"],
            http["criticalRatio"],
        ),
        "auth5xx": classify_ratio(
            sample["authRequests"],
            sample["auth5xx"],
            auth["minimumRequests"],
            auth["warningRatio"],
            auth["criticalRatio"],
        ),
        "todayReadP95Ms": today_state,
        "caregiverTransition5xx": classify_ratio(
            sample["caregiverTransitions"],
            sample["caregiver5xx"],
            caregiver["minimumRequests"],
            caregiver["warningRatio"],
            caregiver["criticalRatio"],
        ),
        "connectorRejected": classify_ratio(
            sample["connectorImports"],
            sample["connectorRejected"],
            connector["minimumImports"],
            connector["warningRatio"],
            connector["criticalRatio"],
        ),
        "deviceContractRejections": classify_count(
            sample["deviceContractRejections"],
            device["warningCount"],
            device["criticalCount"],
        ),
    }


def verify_fixtures(policy: dict[str, Any]) -> None:
    fixtures = load_json(FIXTURES_PATH)
    if fixtures.get("policyVersion") != policy["version"]:
        raise SystemExit("alert fixtures are not bound to the current policy version")
    for fixture in fixtures["fixtures"]:
        actual = classify_fixture(policy, fixture)
        expected = fixture["expected"]
        if actual != expected:
            raise SystemExit(
                f"alert fixture {fixture['name']!r} failed:\nexpected={expected}\nactual={actual}"
            )
    print(f"Verified {len(fixtures['fixtures'])} deterministic alert-policy fixtures.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed rules differ")
    parser.add_argument("--verify-fixtures", action="store_true", help="run deterministic policy fixtures")
    args = parser.parse_args()

    policy = load_json(POLICY_PATH)
    rendered = render_rules(policy)

    if args.check:
        committed = RULES_PATH.read_text() if RULES_PATH.exists() else ""
        if committed != rendered:
            raise SystemExit(
                "committed alert rules are stale; regenerate with: "
                "python .github/scripts/woof-alert-policy.py > ops/alerts/woof-api.rules.yml"
            )
        print("Committed Prometheus alert rules match the versioned Woof alert policy.")
    elif not args.verify_fixtures:
        print(rendered, end="")

    if args.verify_fixtures:
        verify_fixtures(policy)


if __name__ == "__main__":
    main()
