/**
 * San Francisco user profiles for seeding
 * Realistic personas based on SF demographics and culture
 */

export interface SeedUser {
  handle: string;
  email: string;
  password: string;
  bio: string;
  neighborhood: string;
  occupation: string;
  interests: string[];
  demographics: {
    ageRange: string;
    lifestyle: string;
  };
}

export const sfUsers: SeedUser[] = [
  {
    handle: 'techie_sarah',
    email: 'sarah@example.com',
    password: 'password123',
    bio: 'Software engineer at a startup in SoMa. Love taking my golden to Crissy Field on weekends! 🐕',
    neighborhood: 'Mission District',
    occupation: 'Software Engineer',
    interests: ['hiking', 'tech', 'coffee', 'beach-walks'],
    demographics: { ageRange: '28-35', lifestyle: 'active-professional' },
  },
  {
    handle: 'marina_mike',
    email: 'mike@example.com',
    password: 'password123',
    bio: 'Finance professional and rescue dog dad. Always up for a Fort Funston adventure!',
    neighborhood: 'Marina District',
    occupation: 'Finance',
    interests: ['fitness', 'ocean', 'rescue-advocacy', 'running'],
    demographics: { ageRange: '30-40', lifestyle: 'fitness-enthusiast' },
  },
  {
    handle: 'artist_jen',
    email: 'jen@example.com',
    password: 'password123',
    bio: 'Graphic designer and dog mom to the cutest corgi. Love Dolores Park hangs! 🎨🐾',
    neighborhood: 'Mission District',
    occupation: 'Graphic Designer',
    interests: ['art', 'design', 'coffee-shops', 'photography'],
    demographics: { ageRange: '25-32', lifestyle: 'creative' },
  },
  {
    handle: 'noe_valley_dad',
    email: 'david@example.com',
    password: 'password123',
    bio: 'Work-from-home dad with a labradoodle. Always looking for puppy playdates!',
    neighborhood: 'Noe Valley',
    occupation: 'Remote Worker',
    interests: ['family', 'local-community', 'parks', 'training'],
    demographics: { ageRange: '35-45', lifestyle: 'family-oriented' },
  },
  {
    handle: 'yoga_rachel',
    email: 'rachel@example.com',
    password: 'password123',
    bio: 'Yoga instructor + wellness coach. My aussie and I love sunrise walks at Ocean Beach 🧘‍♀️',
    neighborhood: 'Outer Sunset',
    occupation: 'Yoga Instructor',
    interests: ['wellness', 'mindfulness', 'beach', 'nature'],
    demographics: { ageRange: '27-35', lifestyle: 'wellness-focused' },
  },
  {
    handle: 'chef_marcus',
    email: 'marcus@example.com',
    password: 'password123',
    bio: 'Chef at a Mission restaurant. My pit bull is the sweetest! Breaking stereotypes one walk at a time.',
    neighborhood: 'Mission District',
    occupation: 'Chef',
    interests: ['food', 'rescue-advocacy', 'community', 'nightlife'],
    demographics: { ageRange: '28-38', lifestyle: 'service-industry' },
  },
  {
    handle: 'pacific_heights_alex',
    email: 'alex@example.com',
    password: 'password123',
    bio: 'Real estate agent with two french bulldogs. Alta Plaza regular! 🏡',
    neighborhood: 'Pacific Heights',
    occupation: 'Real Estate',
    interests: ['real-estate', 'luxury', 'networking', 'small-dogs'],
    demographics: { ageRange: '32-42', lifestyle: 'upscale-professional' },
  },
  {
    handle: 'bernal_emma',
    email: 'emma@example.com',
    password: 'password123',
    bio: 'Teacher and proud border collie mom. Love the Bernal Heights community!',
    neighborhood: 'Bernal Heights',
    occupation: 'Teacher',
    interests: ['education', 'community', 'hiking', 'agility'],
    demographics: { ageRange: '29-36', lifestyle: 'community-focused' },
  },
  {
    handle: 'dogpatch_sam',
    email: 'sam@example.com',
    password: 'password123',
    bio: 'Product manager at a tech company. My husky needs ALL the exercise! 🏃‍♂️',
    neighborhood: 'Dogpatch',
    occupation: 'Product Manager',
    interests: ['tech', 'hiking', 'active-lifestyle', 'adventure'],
    demographics: { ageRange: '28-34', lifestyle: 'active-professional' },
  },
  {
    handle: 'sunset_lisa',
    email: 'lisa@example.com',
    password: 'password123',
    bio: 'Surfer girl with a surf dog! We practically live at Ocean Beach 🏄‍♀️🌊',
    neighborhood: 'Outer Sunset',
    occupation: 'Surf Instructor',
    interests: ['surfing', 'ocean', 'beach', 'outdoors'],
    demographics: { ageRange: '24-30', lifestyle: 'outdoor-enthusiast' },
  },
  {
    handle: 'richmond_kevin',
    email: 'kevin@example.com',
    password: 'password123',
    bio: 'Data scientist and beagle dad. Golden Gate Park is our second home!',
    neighborhood: 'Richmond District',
    occupation: 'Data Scientist',
    interests: ['data', 'science', 'parks', 'nature-walks'],
    demographics: { ageRange: '30-37', lifestyle: 'analytical-minded' },
  },
  {
    handle: 'castro_tony',
    email: 'tony@example.com',
    password: 'password123',
    bio: 'Nurse at UCSF. My rescue terrier keeps me active after long shifts!',
    neighborhood: 'Castro',
    occupation: 'Nurse',
    interests: ['healthcare', 'rescue', 'fitness', 'lgbtq-community'],
    demographics: { ageRange: '31-40', lifestyle: 'healthcare-professional' },
  },
  {
    handle: 'haight_maya',
    email: 'maya@example.com',
    password: 'password123',
    bio: 'Musician and vintage store owner. My shepherd mix is my bandmate 🎸',
    neighborhood: 'Haight-Ashbury',
    occupation: 'Musician',
    interests: ['music', 'vintage', 'arts', 'counterculture'],
    demographics: { ageRange: '26-33', lifestyle: 'artistic-bohemian' },
  },
  {
    handle: 'soma_jessica',
    email: 'jessica@example.com',
    password: 'password123',
    bio: 'UX designer living the startup life. My poodle mix comes to the office every day!',
    neighborhood: 'SoMa',
    occupation: 'UX Designer',
    interests: ['design', 'startups', 'innovation', 'coworking'],
    demographics: { ageRange: '27-33', lifestyle: 'startup-culture' },
  },
  {
    handle: 'potrero_chris',
    email: 'chris@example.com',
    password: 'password123',
    bio: 'Architect with a great dane. Yes, in a SF apartment! Love Potrero Hill views.',
    neighborhood: 'Potrero Hill',
    occupation: 'Architect',
    interests: ['architecture', 'design', 'large-breeds', 'city-views'],
    demographics: { ageRange: '33-42', lifestyle: 'design-professional' },
  },
  {
    handle: 'north_beach_maria',
    email: 'maria@example.com',
    password: 'password123',
    bio: 'Italian restaurant owner. My two chihuahuas are the unofficial mascots! 🍝',
    neighborhood: 'North Beach',
    occupation: 'Restaurant Owner',
    interests: ['food', 'italian-culture', 'small-dogs', 'hospitality'],
    demographics: { ageRange: '35-50', lifestyle: 'business-owner' },
  },
  {
    handle: 'russian_hill_elena',
    email: 'elena@example.com',
    password: 'password123',
    bio: 'Fashion buyer with impeccable taste. My cavapoo is always runway-ready! 👗',
    neighborhood: 'Russian Hill',
    occupation: 'Fashion Buyer',
    interests: ['fashion', 'luxury', 'style', 'grooming'],
    demographics: { ageRange: '29-38', lifestyle: 'fashion-forward' },
  },
  {
    handle: 'hayes_valley_omar',
    email: 'omar@example.com',
    password: 'password123',
    bio: 'Coffee roaster and cafe owner. Dog-friendly vibes always! ☕',
    neighborhood: 'Hayes Valley',
    occupation: 'Coffee Shop Owner',
    interests: ['coffee', 'small-business', 'community', 'sustainability'],
    demographics: { ageRange: '30-40', lifestyle: 'entrepreneur' },
  },
  {
    handle: 'presidio_amy',
    email: 'amy@example.com',
    password: 'password123',
    bio: 'Environmental scientist. My lab and I explore every trail in the Presidio!',
    neighborhood: 'Presidio Heights',
    occupation: 'Environmental Scientist',
    interests: ['environment', 'science', 'hiking', 'conservation'],
    demographics: { ageRange: '32-40', lifestyle: 'eco-conscious' },
  },
  {
    handle: 'financial_jason',
    email: 'jason@example.com',
    password: 'password123',
    bio: 'Investment banker who makes time for my bulldog. Work hard, play harder!',
    neighborhood: 'Financial District',
    occupation: 'Investment Banker',
    interests: ['finance', 'business', 'networking', 'luxury'],
    demographics: { ageRange: '30-45', lifestyle: 'high-powered' },
  },
];
